#!/bin/bash

#Author: group1
#Date: 02/21/2023

#### Description: Installation of sonarqube

#How to install and configure SonarQube on CentOS 7
#Follow below steps successively to install sonarqube on your centOS server. This process need to be run as a regular user ( Sonarqube doesnt work when you start it as root user).


su - vagrant
sudo yum update -y
sudo yum install java-11-openjdk-devel -y
sudo yum install java-11-openjdk -y
cd /opt
sudo yum install wget -y
sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.3.0.51899.zip
sudo yum install unzip -y
sudo unzip /opt/sonarqube-9.3.0.51899.zip
sudo chown -R vagrant:vagrant /opt/sonarqube-9.3.0.51899
cd sonarqube-9.3.0.51899
cd bin
cd linux-x86-64
./sonar.sh start

$ sudo firewall-cmd --permanent --add-port=9000/tcpcd

$ sudo firewall-cmd --reload
